### ISSUE TITLE
Experience verificator always returns issue

### ISSUE THREAD

**Issue by artptz** [Robak132/WFRP4e-macros-and-more#19]
Even running the macro on a new Character or after executing it and correcting issues, it still flags issues with the actor sheet.
Running on Foundry V12.331, WFRP Core 8.5.1

**Comment by Robak132** [comment]
Fixed in new version 🥳

**Comment by artptz** [comment]
I updated to new version anf Foundry V13.351, all seems to work but skill checks still shows an issue when verifying, then the UI says there are no mismatches

Could it be the issue raises if someonecombines Species and Class skill, e.g. 5 points from Species and 10 points from Starting skill?

<img width="838" height="590" alt="Image" src="https://github.com/user-attachments/assets/39bfad1b-d2f4-437c-9bf5-13ce2b6fd6df" />

**Comment by Robak132** [comment]
You probably set all 15 charm points into "profession" so verificator warns that "race" points are not satified, remove all charm points from log and distribute them 10 for prof and 5 for race
